### PR TITLE
Use odesk/phystrix ~2.0

### PR DESCRIPTION
**Pull request by Henridv**
issue #9

### CODE REVIEW

**Comment by lcf** [comment]
looks like there is a problem with travis, although this PR itself is good.
the build passes for php 5.6. 
would happen to have the time to fix the build @Henridv ? we could remove 5.5 and 5.4 from the list of PHP versions we build against, that is excessive IMO

**Comment by Henridv** [comment]
I could do that. Do you prefer a separate PR for this?

**Comment by lcf** [comment]
up to you, I think it's easier to put all of that in the this PR (even though I do realize these are unrelated things)

**Comment by Henridv** [comment]
I finally got around to updating the travis config :-)

**Pull request closed without merging**
